baseURL = "https://bbog.1-hnr.com"
theme = 'hugo-bearblog'
title = "ä¸€ä¸ªæ²³å—äºº"
author = "Leran"
copyright = "Copyright Â© 2023, Bai Leran."
languageCode = "zh-CN"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "ğŸŒˆğŸ™ŒğŸŒˆ"
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "Blog of ğŸŒˆğŸ™ŒğŸŒˆ"
  # hideMadeWithLine = true

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  dateFormat = "2006-01-02"